import React from 'react'
import './About.css'
import about_img from '../../assets/banner.png'

const About = () => {
  return (
    <div className='about'>
        <h3> ABOUT INFOGRAPH AI</h3>
        <div className="loc">
            <div className="about-left">
                <img src={about_img} alt='about_image' className= 'about-img'/>
            </div>
            <div className="about-right">
                <p>    InfoGraphAI combines the power of artificial intelligence
                    and data visualization to create compelling and informative visuals.
                    To create an InfoGraphic, click on the create button. You will be
                    directed to a page where you can paste the contents of your document. 
                    <br/>
                    <br/>
                       After submiting your text, you will be provided  with a summary
                    which will be used to create the infographic. You can edit it by 
                    clicking on the edit button to suite you.
                    <br/>
                    <br/>
                       You can delete the text if you want to create another summary or 
                    copy it unto the clipboard in case you might need it again.
                    <br/>
                    <br/>
                    To generate your infographic, you have two options.
                    <br/> 
                    - Perfect  InfoGraphics<br/>
                        - These infographics are created with templates generated form
                          canva and the text from your summary.<br/>
                    
                    -AI Generated InfoGraphics<br/>
                        -These infographics are automatically generated by an ImageGenerator
                        from openAI's API. The text on these infographics are not clear
                        so you will have to edit. <br/>
                        -In the image editor right click on the image and select 'save image as..'
                        on it and saving it and in the image editor, click on 'browse here'
                        and select the image from the pop-up menu.<br/>
                        -Edit it to suite you.
                </p>
            </div>
        </div>
        <p><hr/></p>
    </div>
  )
}

export default About
